name: cidade_segura2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 #Pacote de icones e temas do iOs
  firebase_core: ^2.5.0 #inicialização e configuração da plataforma Firebase
  firebase_auth: ^4.2.5 #Autenticção do usuario no FIrebase
  location: ^4.4.0 #Localição do usuario
  google_maps_flutter: ^2.2.3 #Mapa
  geolocator: ^9.0.2 #Geolocalizador
  line_awesome_flutter: ^2.0.0 #Icones customizados
  image_picker: ^0.8.6 #Obtem imagens da camera ou galeria
  splashscreen: ^1.3.5 #(Visual) Adiciona uma imagem a tela de inicialização
  flutter_launcher_icons: ^0.11.0 #(Visual) Adiciona um icone ao aplicativo
  firebase_storage: ^11.0.10 #Armazena arquivos como imagens e videos na nuvem
  http: ^0.13.5 #fazer solicitações HTTP para APIs ou servidores da web e receber respostas para processá-las
  cloud_firestore: ^4.3.1 #Armazena dados na nuvem
  googleapis: ^10.0.0 #APIs do Goolge
  get: ^4.6.5 #Gerenciamento de estados
  modal_bottom_sheet: ^2.1.2 #exibir folhas modais de material design com mais facilidade e flexibilidade
  flutter_native_splash: ^2.2.16 #Configurar e exibir uma tela de splash nativa
  google_fonts: ^4.0.3 #Fontes do Google
  flutter_otp_text_field: ^1.1.1 #Autenticção de 2 Fatores (2FA)
  otp_text_field: ^1.1.3 #Campo de texto para código do autenticador
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5 #biblioteca de gerenciamento de estado, permite compartilhar dados e atualizar widgets com mais facilidade
  flutter_screenutil: ^5.6.1 #torna a interface do usuário responsiva em diferentes dispositivos

flutter_icons: #Icone do aplicativo
    image_path: "assets/app/icon.png"
    ios: true
    remove_aplpha_ios: true
    android: "launcher_icon"
    adaptive_icon_background: '#FFFFFF'
    adaptive_icon_foreground: 'assets/app/icon-android.png'

flutter_native_splash: #Tela de inicio do aplicativo
  color: '#f7f6f1'
  color_dark: '#272727'
  image: 'assets/app/splash.png'
  image_dark: 'assets/app/splash.png'
  android: true
  ios: true

  android_12: #Metodo obrigatorio para versões a partir do Android 12
    image: assets/images/splash_screen/city-logo.png
    icon_background_color: '#f7f6f1'
    image_dark: assets/images/splash_screen/city-logo.png
    icon_background_color_dark: '#272727'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/images/splash_screen/city-logo.png
    - assets/images/bookmark_icon/bookmark-icon.png
    - assets/images/icon/512.png
    - assets/logo/Google_Logo.png
    - assets/images/welcome_images/welcome-screen-image.png
    - assets/images/forget_password/forget-password.png
    - assets/images/profile/profile-pic.jpg
    - assets/images/splash_screen/splash-image.png
    - assets/images/splash_screen/splash-top-icon.png
    - assets/app/icon.png
    - assets/app/icon-android.png
    - assets/app/splash.png
