// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmyL-yI_UfwyPMZJXn-304f68E20PRpko',
    appId: '1:94786209859:android:e1f6454f3b9e916db62cf6',
    messagingSenderId: '94786209859',
    projectId: 'cidadesegura2',
    storageBucket: 'cidadesegura2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyXnVv7phrYRCfi9rNRHSUWrcR1SymFyk',
    appId: '1:94786209859:ios:189a766bcb6befd2b62cf6',
    messagingSenderId: '94786209859',
    projectId: 'cidadesegura2',
    storageBucket: 'cidadesegura2.appspot.com',
    androidClientId: '94786209859-074di2jvf2mtt0imubtbu9to4civ4tc1.apps.googleusercontent.com',
    iosClientId: '94786209859-gmtjhfd556vutf59pi4rral1tlee0ndq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cidadeSegura2',
  );
}
